name: DingTalk Release Notification

on:
  create

permissions:
  contents: read

jobs:
  release-helper:
    permissions:
      contents: write  # for actions-cool/release-helper to create releases
    if: github.event.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Send to Ant Design Web3 DingGroup
        uses: actions-cool/release-helper@v2
        with:
          trigger: 'tag'
          branch: 'main'
          dingding-token: ${{ secrets.WEB3_DINGDING_BOT_TOKEN }}
          msg-title: '{{v}} 发布日志'
          msg-poster: 'https://gw.alipayobjects.com/mdn/rms_08e378/afts/img/A*zx7LTI_ECSAAAAAAAAAAAABkARQnAQ'
          msg-footer: '💬 前往 [**Ant Design Web3 Releases**]({{url}}) 查看更新日志  🐦 twitter: https://twitter.com/AntDesignWeb3'
          prettier: true
          prerelease-notice: true
          prerelease-filter: '-, a, b, A, B'
